// --------------------------------------------------
// DOCX output
// --------------------------------------------------
//
// Converts structured transcript records into a Word
// document. The document is generated entirely in the
// browser using the docx library loaded from a CDN.
//

const DOCX_LIBRARY_URL =
    "https://cdn.jsdelivr.net/npm/docx@9.7.1/+esm";


export async function createCombinedDOCX(
    records,
    title = "Memora — Combined Transcription"
) {

    const {
        Document,
        Paragraph,
        TextRun,
        HeadingLevel,
        Packer
    } = await import(DOCX_LIBRARY_URL);

    const children = [];

    function createMetadataParagraph(label, value) {
        return new Paragraph({
            children: [
                new TextRun({
                    text: `${label}: `,
                    bold: true,
                    size: 20
                }),
                new TextRun({
                    text: String(value),
                    size: 20
                })
            ],
            spacing: {
                after: 60
            }
        });
    }

    function createTranscriptParagraph(text) {
        const lines = String(text).split(/\r?\n/);
        const children = [];

        lines.forEach((line, index) => {
            if (index > 0) {
                children.push(
                    new TextRun({
                        break: 1,
                        size: 24
                    })
                );
            }

            children.push(
                new TextRun({
                    text: line,
                    size: 24
                })
            );
        });

        return new Paragraph({
            children,
            spacing: {
                after: 360,
                line: 360
            }
        });
    }

    children.push(
        new Paragraph({
            text: title,
            heading: HeadingLevel.TITLE,
            spacing: {
                after: 360
            }
        })
    );

    for (let index = 0; index < records.length; index++) {

        const record = records[index];

        children.push(
            new Paragraph({
                text:
                    record.recordingFilename ||
                    record.filename ||
                    "Untitled recording",
                heading: HeadingLevel.HEADING_1,
                spacing: {
                    before: index === 0 ? 0 : 480,
                    after: 120
                }
            })
        );

        children.push(
            createMetadataParagraph(
                "Recording date",
                record.recordingDate || "Date unknown"
            )
        );

        children.push(
            createMetadataParagraph(
                "Duration",
                record.duration || "Duration unknown"
            )
        );

        children.push(
            createMetadataParagraph(
                "Voice Memo ID",
                record.voiceMemoId || "Unknown"
            )
        );

        children.push(
            createMetadataParagraph(
                "Whisper model",
                record.whisperModel || "Unknown"
            )
        );

        children.push(
            new Paragraph({
                text: "",
                spacing: {
                    after: 240
                }
            })
        );

        children.push(
            createTranscriptParagraph(
                record.transcript || ""
            )
        );
    }

    const document = new Document({
        creator: "Memora",
        title,
        description:
            "Combined transcription generated by Memora.",
        styles: {
            default: {
                document: {
                    run: {
                        font: "Aptos",
                        size: 24
                    }
                }
            }
        },
        sections: [
            {
                children
            }
        ]
    });

    return Packer.toBlob(document);
}

